name: rbs-collection-updater

on:
  schedule:
    - cron: "0 0 1 * *" # Run monthly
  workflow_dispatch:

jobs:
  build:
    uses: sue445/workflows/.github/workflows/rbs-collection-updater.yml@main
    with:
      assignees: sue445
      auto-merge: true
    secrets:
      app-id: ${{ secrets.RUBY_GO_GEM_BOT_APP_ID }}
      private-key: ${{ secrets.RUBY_GO_GEM_BOT_PRIVATE_KEY }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
